### ISSUE TITLE
May I ask how can I draw the figure 4A

### ISSUE THREAD

**Issue by zqaccepted** [vkola-lab/brain2020#17]
HI shangran,
Thank your attention. May I ask how can I plot the Fig4A ? Due to my programming ability, I would like to ask how do I draw (iii) based on the riskmap, and how do I superimpose (i) and (ii)? I did not find the code to generate this figure.
Thank you very much

**Comment by shangranq** [comment]
Hi we indeed didn't provide the code for Figure4A. Given the riskmap, drawing iii can be done by finding the contour using from skimage.segmentation import find_boundaries. To superimpose any two figures, you can do img1 = cv2.imread('somefile'), img2 = cv2.imread('somefile'). then combine the two by img = 0.5 * img1 + 0.5 * img2 for example. The number 0.5 can be any other number since it controls the transparency. then you can imsave(img) to get your outcome.

**Comment by zqaccepted** [comment]
thank your kindly help.
