### ISSUE TITLE
about fcn network accuracy

### ISSUE THREAD

**Issue by Godthumb** [vkola-lab/brain2020#20]
i have download your code and running it .but i found i got poor accuracy (about 60%)when i run the fcn network and it converenge difficultly.So i curious about what accuracy you got when run the fcn,i don't read about in paper.expect your  reply.

**Comment by shangranq** [comment]
Hi Godthumb, what you just observed is actually correct! During the training process, we are feeding random patches to the FCN model. Thus the performance you observed is the averaged accuracy over all patches, including background patches, patches that are weakly correlated to label (like frontotemporal lobe), and patches that are strongly correlated to the label (like hippocampus). The MCC heatmap from the paper reported the distribution of accuracy over all locations. The heatmap values were then combined and used as the input to another MLP model to yield individual-level prediction. The ROC curves that we reported are from the MLP model instead of the FCN model. Hope this is helpful!
