### ISSUE TITLE
May I ask how to draw the Figure 6 through t-SNE

### ISSUE THREAD

**Issue by yan-bin1234** [vkola-lab/brain2020#23]
Hi shangranq, I sincerely hope to get your reply. Due to my programming ability, I would like to ask how do I draw the Figure 6.  I don't know much about t-SNE, but want to make a visualization of my dataset through t-SNE. Can you provide the code for this，sincerely thanks for your help.

**Comment by shangranq** [comment]
Hi, maybe you can take a look at this website which explains how to generate a t-SNE plot using python. https://towardsdatascience.com/visualising-high-dimensional-datasets-using-pca-and-t-sne-in-python-8ef87e7915b

Since you will apply the plot to your dataset, I believe following the link above should be able to help you achieve that. Thanks.
